# @generated by tools/generate_from_policy.py; do not edit by hand.
from __future__ import annotations

PROTOCOL_VERSION = 1
SUPPORTED_REQUEST_KINDS = frozenset(['login', 'logout', 'get', 'get-batch', 'refresh', 'erase'])
SUPPORTED_OPERATIONS = frozenset(['read', 'publish'])
SUPPORTED_COMMANDS = frozenset(['install', 'ci', 'publish', 'search', 'view'])
SUPPORTED_AUTH_TYPES = frozenset(['bearer', 'basic'])
SUPPORTED_CACHE = frozenset(['never', 'session', 'expires'])
SUPPORTED_GRANULARITY = frozenset(['registry', 'scope', 'package'])
ERROR_KINDS = frozenset(['url-not-supported', 'not-found', 'operation-not-supported', 'other'])
TRUSTED_LOCATION_KINDS = frozenset(['builtin', 'absolute', 'global-bin', 'enterprise'])
ALLOWED_CONFIG_SOURCES = frozenset(['user', 'global'])
DEFAULT_CACHE_POLICY = 'session'
DEFAULT_GRANULARITY = 'registry'
OPERATION_INDEPENDENT_DEFAULT = True
