// @generated by tools/generate_from_policy.py; do not edit by hand.

pub const PROTOCOL_VERSION: u32 = 1;
pub const ACTIONS: &[&str] = &[
    "login",
    "logout",
    "get",
    "get-batch",
    "refresh",
    "erase",
];
pub const OPERATIONS: &[&str] = &[
    "install",
    "publish",
    "search",
    "view",
];
pub const AUTH_TYPES: &[&str] = &[
    "bearer",
    "basic",
];
pub const CACHE_POLICIES: &[&str] = &[
    "never",
    "session",
    "expires",
];
pub const GRANULARITIES: &[&str] = &[
    "registry",
    "scope",
    "package",
];
pub const ERROR_KINDS: &[&str] = &[
    "url-not-supported",
    "not-found",
    "operation-not-supported",
    "other",
];
pub const TRUSTED_LOCATION_KINDS: &[&str] = &[
    "builtin",
    "absolute",
    "global-bin",
    "enterprise",
];
pub const ALLOWED_CONFIG_SOURCES: &[&str] = &[
    "user",
    "global",
];
pub const DEFAULT_CACHE_POLICY: &str = "session";
pub const DEFAULT_GRANULARITY: &str = "registry";
pub const OPERATION_INDEPENDENT_DEFAULT: bool = true;
