from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
POLICY_PATH = ROOT / "spec" / "policy-v1.json"
PYTHON_OUTPUT = ROOT / "tests" / "generated_policy.py"
RUST_OUTPUT = ROOT / "poc" / "rust" / "crates" / "protocol" / "src" / "generated.rs"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate code from spec/policy-v1.json")
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    policy = json.loads(POLICY_PATH.read_text(encoding="utf-8"))
    outputs = {
        PYTHON_OUTPUT: render_python(policy),
        RUST_OUTPUT: render_rust(policy),
    }

    stale: list[Path] = []
    for path, content in outputs.items():
        if args.check:
            existing = path.read_text(encoding="utf-8") if path.exists() else None
            if existing != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")

    if stale:
        for path in stale:
            print(f"stale generated file: {path.relative_to(ROOT)}", file=sys.stderr)
        print("run: python tools/generate_from_policy.py", file=sys.stderr)
        return 1

    return 0


def render_python(policy: dict) -> str:
    wire = policy["wire"]
    resolution = policy["resolution"]
    cache = policy["cache"]

    return "\n".join(
        [
            "# @generated by tools/generate_from_policy.py; do not edit by hand.",
            "from __future__ import annotations",
            "",
            f"PROTOCOL_VERSION = {policy['protocolVersion']}",
            f"SUPPORTED_ACTIONS = frozenset({wire['actions']!r})",
            f"SUPPORTED_OPERATIONS = frozenset({wire['operations']!r})",
            f"SUPPORTED_AUTH_TYPES = frozenset({wire['authTypes']!r})",
            f"SUPPORTED_CACHE = frozenset({wire['cachePolicies']!r})",
            f"SUPPORTED_GRANULARITY = frozenset({wire['granularities']!r})",
            f"ERROR_KINDS = frozenset({wire['errorKinds']!r})",
            f"TRUSTED_LOCATION_KINDS = frozenset({resolution['trustedLocationKinds']!r})",
            f"ALLOWED_CONFIG_SOURCES = frozenset({resolution['allowedConfigSources']!r})",
            f"DEFAULT_CACHE_POLICY = {cache['defaultPolicy']!r}",
            f"DEFAULT_GRANULARITY = {cache['defaultGranularity']!r}",
            f"OPERATION_INDEPENDENT_DEFAULT = {cache['operationIndependentDefault']!r}",
            "",
        ]
    )


def render_rust(policy: dict) -> str:
    wire = policy["wire"]
    resolution = policy["resolution"]
    cache = policy["cache"]

    return "\n".join(
        [
            "// @generated by tools/generate_from_policy.py; do not edit by hand.",
            "",
            f"pub const PROTOCOL_VERSION: u32 = {policy['protocolVersion']};",
            f"pub const ACTIONS: &[&str] = &{rust_string_array(wire['actions'])};",
            f"pub const OPERATIONS: &[&str] = &{rust_string_array(wire['operations'])};",
            f"pub const AUTH_TYPES: &[&str] = &{rust_string_array(wire['authTypes'])};",
            f"pub const CACHE_POLICIES: &[&str] = &{rust_string_array(wire['cachePolicies'])};",
            f"pub const GRANULARITIES: &[&str] = &{rust_string_array(wire['granularities'])};",
            f"pub const ERROR_KINDS: &[&str] = &{rust_string_array(wire['errorKinds'])};",
            f"pub const TRUSTED_LOCATION_KINDS: &[&str] = &{rust_string_array(resolution['trustedLocationKinds'])};",
            f"pub const ALLOWED_CONFIG_SOURCES: &[&str] = &{rust_string_array(resolution['allowedConfigSources'])};",
            f"pub const DEFAULT_CACHE_POLICY: &str = {json.dumps(cache['defaultPolicy'])};",
            f"pub const DEFAULT_GRANULARITY: &str = {json.dumps(cache['defaultGranularity'])};",
            f"pub const OPERATION_INDEPENDENT_DEFAULT: bool = {str(cache['operationIndependentDefault']).lower()};",
            "",
        ]
    )


def rust_string_array(values: list[str]) -> str:
    rendered = ["["]
    rendered.extend(f"    {json.dumps(value)}," for value in values)
    rendered.append("]")
    return "\n".join(rendered)


if __name__ == "__main__":
    raise SystemExit(main())
