from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
POLICY_PATH = ROOT / "spec" / "policy-v1.json"
PYTHON_OUTPUT = ROOT / "tests" / "generated_policy.py"
RUST_OUTPUT = ROOT / "poc" / "rust" / "crates" / "protocol" / "src" / "generated.rs"
POLICY_SUMMARY_OUTPUT = ROOT / "spec" / "generated-policy-summary.md"
VECTOR_OUTPUT = ROOT / "tests" / "generated_protocol_vectors.json"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate code from spec/policy-v1.json")
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    policy = json.loads(POLICY_PATH.read_text(encoding="utf-8"))
    outputs = {
        PYTHON_OUTPUT: render_python(policy),
        RUST_OUTPUT: render_rust(policy),
        POLICY_SUMMARY_OUTPUT: render_policy_summary(policy),
        VECTOR_OUTPUT: render_vectors(policy),
    }

    stale: list[Path] = []
    for path, content in outputs.items():
        if args.check:
            existing = path.read_text(encoding="utf-8") if path.exists() else None
            if existing != content:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")

    if stale:
        for path in stale:
            print(f"stale generated file: {path.relative_to(ROOT)}", file=sys.stderr)
        print("run: python tools/generate_from_policy.py", file=sys.stderr)
        return 1

    return 0


def render_python(policy: dict) -> str:
    wire = policy["wire"]
    resolution = policy["resolution"]
    cache = policy["cache"]

    return "\n".join(
        [
            "# @generated by tools/generate_from_policy.py; do not edit by hand.",
            "from __future__ import annotations",
            "",
            f"PROTOCOL_VERSION = {policy['protocolVersion']}",
            f"SUPPORTED_ACTIONS = frozenset({wire['actions']!r})",
            f"SUPPORTED_OPERATIONS = frozenset({wire['operations']!r})",
            f"SUPPORTED_AUTH_TYPES = frozenset({wire['authTypes']!r})",
            f"SUPPORTED_CACHE = frozenset({wire['cachePolicies']!r})",
            f"SUPPORTED_GRANULARITY = frozenset({wire['granularities']!r})",
            f"ERROR_KINDS = frozenset({wire['errorKinds']!r})",
            f"TRUSTED_LOCATION_KINDS = frozenset({resolution['trustedLocationKinds']!r})",
            f"ALLOWED_CONFIG_SOURCES = frozenset({resolution['allowedConfigSources']!r})",
            f"DEFAULT_CACHE_POLICY = {cache['defaultPolicy']!r}",
            f"DEFAULT_GRANULARITY = {cache['defaultGranularity']!r}",
            f"OPERATION_INDEPENDENT_DEFAULT = {cache['operationIndependentDefault']!r}",
            "",
        ]
    )


def render_rust(policy: dict) -> str:
    wire = policy["wire"]
    resolution = policy["resolution"]
    cache = policy["cache"]

    return "\n".join(
        [
            "// @generated by tools/generate_from_policy.py; do not edit by hand.",
            "",
            f"pub const PROTOCOL_VERSION: u32 = {policy['protocolVersion']};",
            f"pub const ACTIONS: &[&str] = &{rust_string_array(wire['actions'])};",
            f"pub const OPERATIONS: &[&str] = &{rust_string_array(wire['operations'])};",
            f"pub const AUTH_TYPES: &[&str] = &{rust_string_array(wire['authTypes'])};",
            f"pub const CACHE_POLICIES: &[&str] = &{rust_string_array(wire['cachePolicies'])};",
            f"pub const GRANULARITIES: &[&str] = &{rust_string_array(wire['granularities'])};",
            f"pub const ERROR_KINDS: &[&str] = &{rust_string_array(wire['errorKinds'])};",
            f"pub const TRUSTED_LOCATION_KINDS: &[&str] = &{rust_string_array(resolution['trustedLocationKinds'])};",
            f"pub const ALLOWED_CONFIG_SOURCES: &[&str] = &{rust_string_array(resolution['allowedConfigSources'])};",
            f"pub const DEFAULT_CACHE_POLICY: &str = {json.dumps(cache['defaultPolicy'])};",
            f"pub const DEFAULT_GRANULARITY: &str = {json.dumps(cache['defaultGranularity'])};",
            f"pub const OPERATION_INDEPENDENT_DEFAULT: bool = {str(cache['operationIndependentDefault']).lower()};",
            "",
        ]
    )


def render_policy_summary(policy: dict) -> str:
    wire = policy["wire"]
    errors = policy["errors"]
    fallback = policy["fallback"]
    resolution = policy["resolution"]
    cache = policy["cache"]
    non_interactive = policy["nonInteractive"]

    lines = [
        "<!-- @generated by tools/generate_from_policy.py; do not edit by hand. -->",
        "",
        "# Generated Policy Summary",
        "",
        "Source: `spec/policy-v1.json`.",
        "",
        "## Wire Values",
        "",
        "| Field | Values |",
        "| --- | --- |",
        f"| Protocol version | `{policy['protocolVersion']}` |",
        f"| Actions | {markdown_values(wire['actions'])} |",
        f"| Operations | {markdown_values(wire['operations'])} |",
        f"| Auth types | {markdown_values(wire['authTypes'])} |",
        f"| Cache policies | {markdown_values(wire['cachePolicies'])} |",
        f"| Granularities | {markdown_values(wire['granularities'])} |",
        f"| Error kinds | {markdown_values(wire['errorKinds'])} |",
        "",
        "## Cache Defaults",
        "",
        "| Setting | Value |",
        "| --- | --- |",
        f"| Default cache policy | `{cache['defaultPolicy']}` |",
        f"| Default granularity | `{cache['defaultGranularity']}` |",
        f"| `cache=expires` requires | {markdown_values(cache['expiresRequires'])} |",
        f"| Operation-independent by default | `{json_bool(cache['operationIndependentDefault'])}` |",
        f"| Stored policies | {markdown_values(cache['storePolicies'])} |",
        f"| Non-stored policies | {markdown_values(cache['doNotStorePolicies'])} |",
        "",
        "## Provider Resolution",
        "",
        "| Setting | Value |",
        "| --- | --- |",
        f"| Allowed config sources | {markdown_values(resolution['allowedConfigSources'])} |",
        f"| Trusted location kinds | {markdown_values(resolution['trustedLocationKinds'])} |",
        f"| Untrusted location kinds | {markdown_values(resolution['untrustedLocationKinds'])} |",
        f"| Ambiguous trusted provider | `{resolution['ambiguousTrustedProvider']}` |",
        f"| Missing provider | `{resolution['missingProvider']}` |",
        "",
        "## Error Outcomes",
        "",
        "| Error kind | Context | Outcome |",
        "| --- | --- | --- |",
    ]

    for kind, rules in errors.items():
        for context, outcome in rules.items():
            lines.append(f"| `{kind}` | `{context}` | `{outcome}` |")

    lines.extend(
        [
            "",
            "## Fallback",
            "",
            "| Context | Outcome |",
            "| --- | --- |",
        ]
    )
    for context, outcome in fallback.items():
        lines.append(f"| `{context}` | `{outcome}` |")

    lines.extend(
        [
            "",
            "## Non-Interactive Behavior",
            "",
            "| Setting | Value |",
            "| --- | --- |",
        ]
    )
    for setting, value in non_interactive.items():
        lines.append(f"| `{setting}` | `{json_value(value)}` |")

    lines.append("")
    return "\n".join(lines)


def render_vectors(policy: dict) -> str:
    version = policy["protocolVersion"]
    registry = "https://registry.example.test/"
    valid_messages = [
        {
            "name": "hello-current-version",
            "message": {"v": [version]},
        },
        {
            "name": "request-login",
            "message": {"v": version, "action": "login", "registry": registry},
        },
        {
            "name": "request-logout",
            "message": {"v": version, "action": "logout", "registry": registry},
        },
        {
            "name": "request-erase",
            "message": {"v": version, "action": "erase", "registry": registry},
        },
        {
            "name": "request-get-install",
            "message": {
                "v": version,
                "action": "get",
                "registry": registry,
                "operation": "install",
                "interactive": False,
            },
        },
        {
            "name": "request-get-publish",
            "message": {
                "v": version,
                "action": "get",
                "registry": registry,
                "operation": "publish",
                "interactive": False,
                "version": "1.2.3",
            },
        },
        {
            "name": "request-get-batch",
            "message": {
                "v": version,
                "action": "get-batch",
                "registry": registry,
                "operation": "install",
                "interactive": False,
                "packages": [
                    {"scope": "@scope", "package": "api-client"},
                    {"scope": "@scope", "package": "ui"},
                ],
            },
        },
        {
            "name": "request-refresh",
            "message": {
                "v": version,
                "action": "refresh",
                "registry": registry,
                "refreshToken": "opaque-refresh-token",
            },
        },
        {
            "name": "response-ok-bearer-session",
            "message": {
                "Ok": {
                    "auth": {"type": "bearer", "token": "token"},
                    "cache": policy["cache"]["defaultPolicy"],
                    "granularity": "scope",
                }
            },
        },
        {
            "name": "response-ok-basic-expires",
            "message": {
                "Ok": {
                    "auth": {"type": "basic", "username": "user", "password": "secret"},
                    "cache": "expires",
                    "expiresAt": 1893456000,
                    "granularity": "registry",
                }
            },
        },
        {
            "name": "response-ok-get-batch",
            "message": {
                "Ok": {
                    "kind": "get-batch",
                    "results": [
                        {
                            "auth": {"type": "bearer", "token": "api"},
                            "granularity": "package",
                        },
                        {
                            "auth": {"type": "bearer", "token": "ui"},
                            "granularity": "package",
                        },
                    ],
                }
            },
        },
    ]
    valid_messages.extend(
        {
            "name": f"response-err-{kind}",
            "message": {"Err": {"kind": kind, "message": f"{kind} example"}},
        }
        for kind in policy["wire"]["errorKinds"]
    )

    invalid_messages = [
        {
            "name": "hello-empty-versions",
            "message": {"v": []},
        },
        {
            "name": "request-unknown-action",
            "message": {"v": version, "action": "store", "registry": registry},
        },
        {
            "name": "request-get-missing-operation",
            "message": {
                "v": version,
                "action": "get",
                "registry": registry,
                "interactive": False,
            },
        },
        {
            "name": "request-get-missing-interactive",
            "message": {
                "v": version,
                "action": "get",
                "registry": registry,
                "operation": "install",
            },
        },
        {
            "name": "request-refresh-missing-token",
            "message": {"v": version, "action": "refresh", "registry": registry},
        },
        {
            "name": "request-publish-missing-version",
            "message": {
                "v": version,
                "action": "get",
                "registry": registry,
                "operation": "publish",
                "interactive": False,
            },
        },
        {
            "name": "response-empty",
            "message": {},
        },
        {
            "name": "response-both-ok-and-err",
            "message": {
                "Ok": {"auth": {"type": "bearer", "token": "token"}},
                "Err": {"kind": "other"},
            },
        },
        {
            "name": "response-bearer-missing-token",
            "message": {"Ok": {"auth": {"type": "bearer"}}},
        },
        {
            "name": "response-expires-missing-expires-at",
            "message": {
                "Ok": {
                    "auth": {"type": "bearer", "token": "token"},
                    "cache": "expires",
                }
            },
        },
        {
            "name": "response-unknown-error-kind",
            "message": {"Err": {"kind": "permission-denied"}},
        },
    ]

    vectors = {
        "generatedFrom": "spec/policy-v1.json",
        "protocolVersion": version,
        "validMessages": valid_messages,
        "invalidMessages": invalid_messages,
    }
    return json.dumps(vectors, indent=2) + "\n"


def rust_string_array(values: list[str]) -> str:
    rendered = ["["]
    rendered.extend(f"    {json.dumps(value)}," for value in values)
    rendered.append("]")
    return "\n".join(rendered)


def markdown_values(values: list[str]) -> str:
    return ", ".join(f"`{value}`" for value in values)


def json_bool(value: bool) -> str:
    return "true" if value else "false"


def json_value(value: object) -> str:
    if isinstance(value, bool):
        return json_bool(value)
    return str(value)


if __name__ == "__main__":
    raise SystemExit(main())
